//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CCUIAudioModuleViewControllerDelegate.h"
#import "CCUIContentModule.h"

@class CCUIAudioModuleViewController, CCUISliderModuleBackgroundViewController, NSString, UIViewController<CCUIContentModuleBackgroundViewController>, UIViewController<CCUIContentModuleContentViewController>;

@interface CCUIAudioModule : NSObject <CCUIContentModule, CCUIAudioModuleViewControllerDelegate>
{
    CCUIAudioModuleViewController *_moduleViewController;
    CCUISliderModuleBackgroundViewController *_backgroundViewController;
}

- (void).cxx_destruct;
- (id)_audioGlyphStateForVolumeLevel:(double)arg1;
- (id)_audioGlyphPackageDescription;
- (void)audioModuleViewController:(id)arg1 volumeDidChange:(float)arg2;
@property(readonly, nonatomic) UIViewController<CCUIContentModuleBackgroundViewController> *backgroundViewController;
@property(readonly, nonatomic) UIViewController<CCUIContentModuleContentViewController> *contentViewController;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

