//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CCUIModuleSliderView.h"

@class UIImpactFeedbackGenerator, UIView;

@interface CCUIVolumeSliderView : CCUIModuleSliderView
{
    _Bool _euDevice;
    float _euVolumeLimit;
    _Bool _euVolumeLimitEnforced;
    UIView *_orangeValueView;
    _Bool _didAcknowledgeThreshold;
    _Bool _didHitThreshold;
    UIImpactFeedbackGenerator *_impactFeedbackGenerator;
}

- (void).cxx_destruct;
- (void)_EUVolumeEnforcementChanged:(id)arg1;
- (void)_EUVolumeLimitChanged:(id)arg1;
- (void)_serverConnectionDied:(id)arg1;
- (void)_unregisterForAVSystemControllerNotifications;
- (void)_registerForAVSystemControllerNotifications;
- (float)_limitedVolumeValue;
- (void)_initializeEUVolumeLimits;
- (void)_handleValueChangeGestureRecognizer:(id)arg1;
- (void)setContinuousSliderCornerRadius:(double)arg1;
- (float)_valueForPanGestureRecognizer:(id)arg1 withAbsoluteReference:(_Bool)arg2;
- (void)_layoutContinuousValueViewForValue:(float)arg1;
- (void)setNumberOfSteps:(unsigned long long)arg1;
- (void)resetThresholdAcknowledgment;
- (id)initWithFrame:(struct CGRect)arg1;

@end

