//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "CCUIContentModuleContentViewController.h"
#import "CCUIGroupRendering.h"
#import "MPVolumeControllerDelegate.h"
#import "MPVolumeDisplaying.h"

@class CALayer, CCUIVolumeSliderView, MPVolumeController, NSString, NSTimer;

@interface CCUIAudioModuleViewController : UIViewController <MPVolumeControllerDelegate, MPVolumeDisplaying, CCUIGroupRendering, CCUIContentModuleContentViewController>
{
    CCUIVolumeSliderView *_sliderView;
    MPVolumeController *_volumeController;
    NSTimer *_updatesCommitTimer;
    float _previousValue;
    float _value;
    _Bool _expanded;
    id <CCUIAudioModuleViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <CCUIAudioModuleViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)volumeControlAvailabilityDidChange;
- (void)volumeController:(id)arg1 volumeValueDidChange:(float)arg2;
@property(readonly, nonatomic) NSString *volumeAudioCategory;
@property(readonly, nonatomic, getter=isOnScreen) _Bool onScreen;
- (void)_sliderValueDidChange:(id)arg1;
@property(readonly, nonatomic) CALayer *punchOutRootLayer;
@property(readonly, nonatomic, getter=isGroupRenderingRequired) _Bool groupRenderingRequired;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willTransitionToExpandedContentMode:(_Bool)arg1;
@property(readonly, nonatomic) double preferredExpandedContentWidth;
@property(readonly, nonatomic) double preferredExpandedContentHeight;
- (void)setGlyphState:(id)arg1;
- (void)setGlyphPackageDescription:(id)arg1;
@property(readonly, nonatomic) float currentVolume;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic, getter=isOnScreenForVolumeDisplay) _Bool onScreenForVolumeDisplay;
@property(readonly, nonatomic) _Bool providesOwnPlatter;
@property(readonly) Class superclass;

@end

